### ISSUE TITLE
NoneType exceptions on most docx files

### ISSUE THREAD

**Issue by jack-rory-staunton** [tantale/docx_utils#1]
When converting a directory of docx to xml, I get the following exception on the majority of files:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-08a0abfc0a68> in <module>
----> 1 opc_to_flat_opc('ASED draft BAA 7.20.2017.docx', 'ASED.xml')

/usr/local/lib/python3.7/site-packages/docx_utils/flatten.py in opc_to_flat_opc(src_path, dst_path)
     95         node = etree.SubElement(root, u"{{{pkg}}}part".format(pkg=pkg), nsmap=ns)
     96         node.attrib[u"{{{pkg}}}name".format(pkg=pkg)] = part.uri
---> 97         node.attrib[u"{{{pkg}}}contentType".format(pkg=pkg)] = part.content_type
     98         if part.content_type.endswith("xml"):
     99             data = etree.SubElement(node, u"{{{pkg}}}xmlData".format(pkg=pkg), nsmap=ns)

src/lxml/etree.pyx in lxml.etree._Attrib.__setitem__()

src/lxml/apihelpers.pxi in lxml.etree._setAttributeValue()

src/lxml/apihelpers.pxi in lxml.etree._utf8()

TypeError: Argument must be bytes or unicode, got 'NoneType'

```
It seems that this may arise "intentionally" (https://bugs.python.org/issue28236) from the lxml package code, but is there anything that can be done to handle these NoneType fields so that these files can be converted properly?

**Comment by tantale** [comment]
Inside the docx archive, pathnames should be absolute posix paths.
But sometimes the leading "/" is missing, so the content type is not found.
I can fix this issue but I need an docx example to be sure.

Can you attach one of your faulty docx for analysis?

**Comment by tantale** [comment]
Also, some docx archives may contain invalid entries like `[Trash]/0000.dat` with no registered content type. Those files could be ignored…

**Comment by jack-rory-staunton** [comment]
Unfortunately I can't share the files I'm working with - I will try to find one that fails which I can share. I'm not sure about your second comment on invalid entries - if you're referring to files like 0000.dat, I can confirm that's not the case (it's a valid docx that Word can properly convert to pdf). But if you're referring to an invalid field somewhere in a valid docx, I would want to "repair" the field to some valid default value and process the file. Is this not possible? Obviously I have no way of knowing what fields are in the files without e.g. using docx_utils.

**Comment by tantale** [comment]
Can you unzip a faulty docx and send me the Content-type.xml file and the list of unzipped files (a directory tree would be better).
Regards.
